name: rune_example
description: Phase 1 demo app for the rune package.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  rune:
    path: ../
  rune_provider:
    path: ../packages/rune_provider
  rune_responsive_sizer:
    path: ../packages/rune_responsive_sizer

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
