name: rune
description: Converts Dart widget code strings into real Flutter widgets at runtime via AST interpretation.
version: 0.0.8
repository: https://github.com/CanArslanDev/rune
homepage: https://github.com/CanArslanDev/rune
issue_tracker: https://github.com/CanArslanDev/rune/issues
topics:
  - ui
  - runtime
  - server-driven-ui
  - dynamic
  - analyzer

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  analyzer: ^6.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
