import 'package:flutter/material.dart';
import 'package:rune/src/builders/widgets/icon_builder.dart' show IconBuilder;
import 'package:rune/src/registry/constant_registry.dart';

/// Seeds [registry] with ~60 common `Icons.*` constants used by the
/// Phase 2c [IconBuilder]. Consumers can register additional icons on the
/// `RuneConfig.constants` field directly.
void registerPhase2cIcons(ConstantRegistry registry) {
  registry.registerAll('Icons', const <String, Object?>{
    'home': Icons.home,
    'menu': Icons.menu,
    'close': Icons.close,
    'search': Icons.search,
    'settings': Icons.settings,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'star': Icons.star,
    'star_border': Icons.star_border,
    'share': Icons.share,
    'more_vert': Icons.more_vert,
    'more_horiz': Icons.more_horiz,
    'person': Icons.person,
    'people': Icons.people,
    'notifications': Icons.notifications,
    'notifications_none': Icons.notifications_none,
    'email': Icons.email,
    'phone': Icons.phone,
    'add': Icons.add,
    'remove': Icons.remove,
    'edit': Icons.edit,
    'delete': Icons.delete,
    'check': Icons.check,
    'check_circle': Icons.check_circle,
    'warning': Icons.warning,
    'error': Icons.error,
    'info': Icons.info,
    'arrow_back': Icons.arrow_back,
    'arrow_forward': Icons.arrow_forward,
    'arrow_upward': Icons.arrow_upward,
    'arrow_downward': Icons.arrow_downward,
    'expand_more': Icons.expand_more,
    'expand_less': Icons.expand_less,
    'chevron_left': Icons.chevron_left,
    'chevron_right': Icons.chevron_right,
    'play_arrow': Icons.play_arrow,
    'pause': Icons.pause,
    'stop': Icons.stop,
    'skip_next': Icons.skip_next,
    'skip_previous': Icons.skip_previous,
    'refresh': Icons.refresh,
    'cloud_download': Icons.cloud_download,
    'cloud_upload': Icons.cloud_upload,
    'shopping_cart': Icons.shopping_cart,
    'credit_card': Icons.credit_card,
    'visibility': Icons.visibility,
    'visibility_off': Icons.visibility_off,
    'lock': Icons.lock,
    'lock_open': Icons.lock_open,
    'chat': Icons.chat,
    'send': Icons.send,
    'calendar_today': Icons.calendar_today,
    'access_time': Icons.access_time,
    'location_on': Icons.location_on,
    'map': Icons.map,
    'save': Icons.save,
    'print': Icons.print,
    'camera_alt': Icons.camera_alt,
    'image': Icons.image,
    'folder': Icons.folder,
  });
}
